In [ ]:
# Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array ([[1, 6],
      [2, 8],
      [3, 11],
      [3, 10],
      [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [17]:
b = np.mean(a, axis = 0)
b

array([2. , 8.4])

In [16]:
np.mean(b)

5.2

In [18]:
c = np.mean(a, axis = 1)
c

array([3.5, 5. , 7. , 6.5, 4. ])

In [19]:
np.mean(c)

5.2

In [20]:
mean_a = np.mean (a, axis = 0)
mean_a

array([2. , 8.4])

In [ ]:
# Задание 2

In [28]:
a_centered = np.array (a - mean_a)
a_centered 

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [29]:
# Задание 3

In [37]:
a_centered_sp = a_centered.prod(1)
a_centered_sp

array([ 2.4, -0. ,  2.6,  1.6,  1.4])

In [39]:
N = c - 1
N

array([2.5, 4. , 6. , 5.5, 3. ])

In [45]:
v = a_centered_sp / N
v

array([ 0.96      , -0.        ,  0.43333333,  0.29090909,  0.46666667])

In [46]:
w = np.divide(a_centered_sp, N)
w

array([ 0.96      , -0.        ,  0.43333333,  0.29090909,  0.46666667])

In [47]:
v == w

array([ True,  True,  True,  True,  True])

In [48]:
# Задание 4

In [65]:
m = np.cov(a.T)
m

array([[1. , 2. ],
       [2. , 4.3]])

In [67]:
d = m[0, 1]
d

2.0